language: ruby
os: linux
dist: xenial
cache:
  directories:
  - reactor_test/vendor/bundle
rvm:
  - 2.4.5
env:
  jobs:
    - BUNDLE_GEMFILE=Gemfile.rails50
    - BUNDLE_GEMFILE=Gemfile.rails51
    - BUNDLE_GEMFILE=Gemfile
services:
  - docker
before_install:
  - export TZ=Europe/Berlin
  - cd reactor_test
  - gem install bundler
  - travis/docker_login.sh
before_script:
  - travis/docker_start.sh
  - travis/docker_ready.sh
  - cp config/initializers/reactor.rb.example config/initializers/reactor.rb
after_script:
  - cd docker-build
  - docker-compose down --volumes
