language: ruby
os: linux
dist: xenial
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.6
bundler_args: --without production
cache:
  bundler: true
env:
  global:
    - secure: i/jggEOFeCVZdFl38+SvZv6DTvrLCqpqKo7TWNuVxRT6TxUuaE+bmMae1boMelrX3Je3eXnxL7y+I4/dEsPiDxC40Enp9rocOgOcmVATzaIJT1veo4rsq2iUeiYQxZUVH4DWOW+Nc5SbeoPKck17eV/46XUe5l/4XPpfcxvPoVE=
    - secure: c9ybzPqM2uWZxhQPE6vbe4tsL/UnIVOt1Qg5XIpwSqqdOHUoxTALz2f23NuGAcvuVXuSxX4li/Scjq4t/e3O+qYmHbOkWdTb/QgxqC/ZwtdsYsYzN4YkdobyIXWHxVSc0jbwecWhaS42ahDqcakfGcFTaTNv/nMzODbAQw3z0Lk=
    # speed up "gem install nokogiri" by using systems libxml2
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  jobs:
    - TASK=spec
    - TASK=js_spec
services:
  - mysql
script: bundle exec rake $TASK --trace
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - mysql -e "create database fiona_connector_test"
