language: ruby
os: linux
dist: bionic
cache:
  directories:
    - reactor_test/vendor/bundle
rvm:
  - 3.1.2
  - 3.0.4
  - 2.7.5
env:
  jobs:
    - BUNDLE_GEMFILE=Gemfile
services:
  - docker
if: branch =~ /^travis|^develop$|^master$/
before_install:
  - export TZ=Europe/Berlin
  - cd reactor_test
  - gem install bundler -v '~> 2.3'
  - travis/docker_login.sh
before_script:
  - travis/docker_start.sh
  - travis/docker_ready.sh
  - cp config/initializers/reactor.rb.example config/initializers/reactor.rb
after_script:
  - cd docker-build
  - docker-compose down --volumes
jobs:
  include:
  - name: Rubocop
    cache:
      directories:
        - infopark_reactor/vendor/bundle
    before_install:
      - cd infopark_reactor
    before_script: skip
    script: bundle exec rubocop
    after_script: skip
