version: '2'
services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  app:
    image: local/fiona7:latest
    container_name: fiona_reactor
    command: ./start.sh
    environment:
      - LD_LIBRARY_PATH="/fiona/CMS-Fiona-7.0.1/lib/sles:$LD_LIBRARY_PATH"
    ports:
      - "3001:3001"
      - "3002:3002"
      - "3011:3011"
      - "8080:8080"
      - "6000:6000"
      - "6001:6001"
      - "6002:6002"
    links:
      - mysql
    depends_on:
      - mysql
