version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reactor_test
      MYSQL_USER: reactor_user
      MYSQL_PASSWORD: reactor_user
    ports:
      - "3306:3306"
  app:
    image: fiona7_reactor:latest
    container_name: fiona7_reactor
    command: ./start.sh
    environment:
      - LD_LIBRARY_PATH="/fiona/CMS-Fiona-7.0.1/lib/sles:$LD_LIBRARY_PATH"
    ports:
      - "3001:3001"
      - "3002:3002"
      - "3202:3202"
      - "3011:3011"
      - "8080:8080"
    depends_on:
      - db
